Add results about permutations
inQWIRE/QuantumLib pull request #42
Opened 2024-05-05 23:23 UTC by lczielinski

Author: @wjbs 

Add many results to `Permutations.v`, necessary for defining `ZXPerm` in VyZX. Results about:
- injectivity/surjectivity of permutations
- permutation inverse
- well-foundedness of permutatinos
- stacking permutations
- swaps of elements
- permutations on lists
...and some automation.

2024-05-05 23:23 UTC, lczielinski commented on coq-quantumlib.opam
> +  "coq" {>= "8.12"}
Did this automatically, not really sure why

2024-05-17 18:59 UTC, adrianleh requested changes
LGTM overall. Some very useful additions are in here. I left some inline comments for changes that we might want to make.

2024-05-17 18:59 UTC, adrianleh commented on VectorStates.v
> +Lemma testbit_binlist {n : nat} {k : list bool} :
It looks like you're adding a lot of bit manipulation and funbool handling. At this point it seems to me we might want to split it out of VectorStates into a separate file.

2024-05-17 18:59 UTC, adrianleh commented on Permutations.v
> +
Maybe we should scope this file in a new scope as there are some names that might be conflicting with other work

2024-05-17 18:59 UTC, adrianleh commented on Permutations.v
> +Local Notation perm_bdd n f := (forall k, k < n -> f k < n).
I assume `bdd` means bounded but I don't think is very clear. I'd spell that out

2024-05-17 18:59 UTC, adrianleh commented on Permutations.v
> +Local Notation perm_eq n f g := (forall k, k < n -> f k = g k).
Why do we have a fixed n here? To me permutations being equal means that they are both of the same size and then have equal elements

2024-05-27 17:45 UTC, adrianleh commented on VectorStates.v
> +Lemma testbit_binlist {n : nat} {k : list bool} :
I think it's fine to include here

2024-05-27 17:48 UTC, adrianleh commented
@lczielinski We also want to bump the version in `dune-project` and `coq-quantumlib.opam` to 1.5.0

2024-05-27 19:21 UTC, lczielinski commented
Made new files `Bits.v` (the classical bit stuff from `VectorStates.v`), `PermutationAutomation.v` (the second half of `Permutation.v`) and `Modulus.v` (a few lemmas about mod)

2024-05-27 22:14 UTC, adrianleh approved these changes
LGMT

2024-05-27 22:15 UTC, merged